version: 1
disable_existing_loggers: False

formatters:
    simple:
        format: "[%(levelname)-8s] %(asctime)s %(module)s:%(name)s.%(funcName)s():%(lineno)d: %(message)s"
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

loggers:
    airelay:
        level: INFO
        handlers: [console]
        propagate: no
    pytest:
        level: INFO
        handlers: [ console ]
        propagate: no

root:
    level: INFO
    handlers: [console]