name: ruff
on: [ push, pull_request, workflow_dispatch ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ruff-check
        uses: chartboost/ruff-action@v1
        with:
          args: "check --output-format=github"

      - name: Ruff-format
        if: always()
        uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Test with pytest
#        env:
#          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        if: always()
        run: |-
          python -m pip install -r requirements.txt
          pytest ./airelay/test_airelay.py -s --junit-xml=test.xml -m "not uses_tokens"

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.xml


