name: ruff
on: [ push, pull_request, workflow_dispatch ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install ruff
        run: python -m pip install ruff

      - name: Ruff check
        run: ruff check --output-format=github

      - name: Ruff format
        if: always()
        run: ruff format --diff
