name: test
on: [ push, pull_request, workflow_dispatch ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      VALID_THREAD_ID: ${{ secrets.VALID_THREAD_ID }}
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install requirements.txt
        run: python -m pip install -r requirements.txt

      - name: Test with pytest
        if: always()
        run: pytest ./airelay/test_airelay.py -s --junit-xml=test.xml -m "not uses_tokens"

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.xml


